# Generated by Django 4.1.3 on 2022-11-22 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_bakecakeberries_bakecakedecor_bakecakelevels_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'Каталог', 'verbose_name_plural': 'Каталоги'},
        ),
        migrations.AddField(
            model_name='bakecake',
            name='catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.catalog', verbose_name='В каталоге'),
        ),
        migrations.AddField(
            model_name='bakecake',
            name='image',
            field=models.ImageField(blank=True, default='media/BakeCakeImages/no_image.png', null=True, upload_to='media/BakeCakeImages/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='image',
            field=models.ImageField(default='media/BakeCakeImages/no_image.png', upload_to='media/catalog/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='name',
            field=models.CharField(default='На чаепитие', max_length=50, verbose_name='Название'),
        ),
    ]
